name: Swap functional tests

on:
  workflow_dispatch:
  push:
      branches:
        - master
        - main
        - develop
  pull_request:
  
jobs:
    job_functional_tests:
      uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@swap-near
      with:
        branch_for_near: ${{ github.ref }}
        test_filter: '"NEAR or near or Near"'
        branch_for_exchange: 'swap-near'